			/*TABELA (DESC)*/
CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY NOT NULL,
	CLASSIFICACAO VARCHAR(10) NOT NULL,
	C_EXAME ENUM('1','0') NOT NULL,
	C_MEDICAMENTO ENUM('1','0') NOT NULL,
	C_RETORNO ENUM('1','0') NOT NULL,
);