			
			/*BANCO DE DADOS*/
CREATE DATABASE HOSPITAL_MODEL;


			/*TABELA (DESC)*/
CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY NOT NULL,
	CLASSIFICACAO VARCHAR(10),
	C_EXAME ENUM('1','0'),
	C_MEDICAMENTO ENUM('1','0'),
	C_RETORNO ENUM('1','0') 
);